#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "molokai"
    background = "dark"
    default_indent = 4
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false
    enable_vimfiler_welcome = 0
    enable_vimfiler_gitstatus = true
    filemanager = "nerdtree"
    lint_on_the_fly = false

    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
spacevim_autocomplete_method = "depplete"
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'VersionControl'

[[layers]]
name = 'checkers'
show_cursor_error = false

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'git'

[[layers]]
name = 'github'

[[layers]]
name = 'tools'

[[layers]]
name = 'fzf'

[[layers]]
name = 'default'

[[layers]]
name = 'tmux'

[[layers]]
name = 'lang#c'

[[layers]]
name = 'lang#go'

[[layers]]
 name = "lang#rust"

[[layers]]
name = 'lang#python'
enable_typeinfo = true

[[layers]]
name = 'lang#javascript'

[[layers]]
name = 'lang#typescript'

[[layers]]
name = 'lang#sh'

[[layers]]
name = 'lang#groovy'

[[layers]]
name = 'lang#html'

[[layers]]
name = 'lang#markdown'

[[layers]]
name = 'lang#json'

[[layers]]
name = 'lsp'
filetypes = [
    "c",
    "cpp",
    "go",
    "groovy",
    "python",
    "rust",
    "terraform",
    "yaml"
  ]

[[layers]]
name = 'lang#toml'

[[layers]]
name = 'lang#dockerfile'

[[custom_plugins]]
name = "lilydjwg/colorizer"
merged = 0

[[custom_plugins]]
name = "docker/docker"
merged = 0

[[custom_plugins]]
name = "chase/vim-ansible-yaml"
merged = 0

[[custom_plugins]]
name = "martinda/jenkinsfile-vim-syntax"
merged = 0

[[custom_plugins]]
name = "towolf/vim-helm"
merged = 0

[[custom_plugins]]
name = "will133/vim-dirdiff"
merged = 0

[[custom_plugins]]
name = "hashivim/vim-terraform"
merged = 0

[[custom_plugins]]
name = "aklt/plantuml-syntax"
merged = 0

[[custom_plugins]]
name = "tyru/open-browser.vim"
merged = 0

[[custom_plugins]]
name = "weirongxu/plantuml-previewer.vim"
merged = 0
