theme = "monokai"

[editor]
line-number = "relative"
mouse = false
true-color = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-y = ":clipboard-yank" 
C-p = ":clipboard-paste-after"
esc = ["collapse_selection", "keep_primary_selection"]